import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF6750A4),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFE9DDFF),
  onPrimaryContainer: Color(0xFF22005D),
  secondary: Color(0xFF625B71),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFE8DEF8),
  onSecondaryContainer: Color(0xFF1E192B),
  tertiary: Color(0xFF006B5B),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFF79F8DC),
  onTertiaryContainer: Color(0xFF00201A),
  error: Color(0xFFAE2E40),
  errorContainer: Color(0xFFFFDADA),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF40000C),
  background: Color(0xFFFFFBFF),
  onBackground: Color(0xFF1C1B1E),
  outline: Color(0xFF7A757F),
  onInverseSurface: Color(0xFFF4EFF4),
  inverseSurface: Color(0xFF313033),
  inversePrimary: Color(0xFFCFBCFF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF6750A4),
  outlineVariant: Color(0xFFCAC4CF),
  scrim: Color(0xFF000000),
  surface: Color(0xFFFDF8FD),
  onSurface: Color(0xFF1C1B1E),
  surfaceVariant: Color(0xFFE7E0EB),
  onSurfaceVariant: Color(0xFF49454E),
);
