name: wherewithal
description: Personal finance tracker
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  adaptive_theme: ^3.3.0
  cloud_firestore: ^4.9.1
  cloud_firestore_odm: ^1.0.0-dev.68
  cloud_functions: ^4.5.4
  collection: ^1.17.2
  device_info_plus: ^9.1.1
  envied: ^0.3.0+3
  firebase_analytics: ^10.7.1
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_messaging: ^14.7.4
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  get_it: ^7.6.2
  get_it_mixin: ^4.2.1
  go_router: ^9.1.1
  google_sign_in: ^6.1.4
  http: ^1.1.0
  http_parser: ^4.0.2
  image_picker: ^1.0.4
  intl: any
  intl_translation: ^0.18.2
  json_annotation: ^4.8.1
  mime: ^1.0.4
  package_info_plus: ^4.1.0
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.0
  
dependency_overrides:
  graphs: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.3
  cloud_firestore_odm_generator: ^1.0.0-dev.58
  json_serializable: ^6.7.1
  envied_generator: ^0.3.0+3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/flags/