// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLCP0TTL3Hkd8R0a6cNUkDm0VaghjmWXU',
    appId: '1:837134992436:web:6e83eb165d8dd66a6e7661',
    messagingSenderId: '837134992436',
    projectId: 'wherewithal-dc32d',
    authDomain: 'wherewithal-dc32d.firebaseapp.com',
    storageBucket: 'wherewithal-dc32d.appspot.com',
    measurementId: 'G-J1Q02C247X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV2ULZKKd83roTVdyP51zyhzak7j8OiPc',
    appId: '1:837134992436:android:1490acc970653fd16e7661',
    messagingSenderId: '837134992436',
    projectId: 'wherewithal-dc32d',
    storageBucket: 'wherewithal-dc32d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4XXZsG0Iwl_hFMUrPyJC1_fTDXfn7I-A',
    appId: '1:837134992436:ios:b01a38b6bd4c66b16e7661',
    messagingSenderId: '837134992436',
    projectId: 'wherewithal-dc32d',
    storageBucket: 'wherewithal-dc32d.appspot.com',
    androidClientId: '837134992436-7dt4gsdcd5g0skdk5iek6nj3jle6oegi.apps.googleusercontent.com',
    iosClientId: '837134992436-85p8dj5goth1qlbiqlig40ft9t3uugq7.apps.googleusercontent.com',
    iosBundleId: 'com.mak.wherewithal',
  );
}
